
package pl.edu.atena.rest.ws.klient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Akademia", targetNamespace = "http://pl.edu.atena.akademia", wsdlLocation = "http://localhost:8080/EJBSzkol/Akademia?wsdl")
public class Akademia
    extends Service
{

    private final static URL AKADEMIA_WSDL_LOCATION;
    private final static WebServiceException AKADEMIA_EXCEPTION;
    private final static QName AKADEMIA_QNAME = new QName("http://pl.edu.atena.akademia", "Akademia");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EJBSzkol/Akademia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AKADEMIA_WSDL_LOCATION = url;
        AKADEMIA_EXCEPTION = e;
    }

    public Akademia() {
        super(__getWsdlLocation(), AKADEMIA_QNAME);
    }

    public Akademia(WebServiceFeature... features) {
        super(__getWsdlLocation(), AKADEMIA_QNAME, features);
    }

    public Akademia(URL wsdlLocation) {
        super(wsdlLocation, AKADEMIA_QNAME);
    }

    public Akademia(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AKADEMIA_QNAME, features);
    }

    public Akademia(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Akademia(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UbezpieczajacyWService
     */
    @WebEndpoint(name = "UbezpieczajacyWServicePort")
    public UbezpieczajacyWService getUbezpieczajacyWServicePort() {
        return super.getPort(new QName("http://pl.edu.atena.akademia", "UbezpieczajacyWServicePort"), UbezpieczajacyWService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UbezpieczajacyWService
     */
    @WebEndpoint(name = "UbezpieczajacyWServicePort")
    public UbezpieczajacyWService getUbezpieczajacyWServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pl.edu.atena.akademia", "UbezpieczajacyWServicePort"), UbezpieczajacyWService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AKADEMIA_EXCEPTION!= null) {
            throw AKADEMIA_EXCEPTION;
        }
        return AKADEMIA_WSDL_LOCATION;
    }

}
