
package pl.edu.atena.rest.ws.klient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UbezpieczajacyWService", targetNamespace = "http://pl.edu.atena.akademia")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UbezpieczajacyWService {


    /**
     * 
     * @param result
     * @param test
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "insurer", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.Insurer")
    @ResponseWrapper(localName = "insurerResponse", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.InsurerResponse")
    public void insurer(
        @WebParam(name = "name", targetNamespace = "http://pl.edu.atena.akademia")
        String name,
        @WebParam(name = "test", targetNamespace = "http://pl.edu.atena.akademia", mode = WebParam.Mode.INOUT)
        Holder<Integer> test,
        @WebParam(name = "result", targetNamespace = "http://pl.edu.atena.akademia", mode = WebParam.Mode.OUT)
        Holder<Ubezpieczajacy> result);

}
