package pl.atena.edu.akademia.PolisaWSClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolisaWService", targetNamespace = "http://pl.edu.atena.akademia")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolisaWService {


    /**
     * 
     * @param id
     * @return
     *     returns akademia.atena.edu.pl.Polisa
     */
    @WebMethod(operationName = "WyszukajPoliseId")
    @WebResult(name = "polisa", targetNamespace = "http://pl.edu.atena.akademia")
    @RequestWrapper(localName = "WyszukajPoliseId", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.WyszukajPoliseId")
    @ResponseWrapper(localName = "WyszukajPoliseIdResponse", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.WyszukajPoliseIdResponse")
    public Polisa wyszukajPoliseId(
        @WebParam(name = "id", targetNamespace = "http://pl.edu.atena.akademia")
        Long id);

    /**
     * 
     * @param arg0
     * @return
     *     returns akademia.atena.edu.pl.Polisa
     */
    @WebMethod(operationName = "RejestracjaPolisy")
    @WebResult(name = "polisa", targetNamespace = "http://pl.edu.atena.akademia")
    @RequestWrapper(localName = "RejestracjaPolisy", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.RejestracjaPolisy")
    @ResponseWrapper(localName = "RejestracjaPolisyResponse", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.RejestracjaPolisyResponse")
    public Polisa rejestracjaPolisy(
        @WebParam(name = "arg0", targetNamespace = "")
        Polisa arg0);

    /**
     * 
     * @param numer
     * @return
     *     returns akademia.atena.edu.pl.Polisa
     */
    @WebMethod(operationName = "WyszukajPolise")
    @WebResult(name = "polisa", targetNamespace = "http://pl.edu.atena.akademia")
    @RequestWrapper(localName = "WyszukajPolise", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.WyszukajPolise")
    @ResponseWrapper(localName = "WyszukajPoliseResponse", targetNamespace = "http://pl.edu.atena.akademia", className = "akademia.atena.edu.pl.WyszukajPoliseResponse")
    public Polisa wyszukajPolise(
        @WebParam(name = "numer", targetNamespace = "http://pl.edu.atena.akademia")
        String numer);

}
